Core compatibility update
specklesystems/Objects pull request #6
Opened 2020-09-29 18:19 UTC by didimitrie

Core compatibility: 
- first implementation of `GetAvailableConverters`, &
- `LoadConverter` for a specific app.

Extras: 
- adds rh and rvt converters as local dependencies
- adds post build action: post build copies dll to `%appdata%/Speckle/Kits/Objects`

2020-09-30 18:55 UTC, teocomi reviewed
Should GridLine be under a different namespace than BuiltElements?

2020-09-30 18:55 UTC, teocomi commented on Objects.sln
> +EndProject
Why adding the other projs as references? I find it cleaner to just have Objects referenced in each converter instead....

2020-09-30 19:03 UTC, teocomi commented on Objects/ObjectsKit.cs
> +    public ISpeckleConverter LoadConverter(string app)
Not sure why Objects should be loading the converters? Should this just be down to the connectors instead?
Let's discuss!

2020-09-30 19:29 UTC, didimitrie commented on Objects.sln
> +EndProject
I needed to operate changes that could impact all converters. This way it was easier for me to find all references.

2020-09-30 19:30 UTC, didimitrie commented on Objects/Objects.csproj
> +    <AssemblyName>Objects</AssemblyName>
In this case I thought not having Speckle in the name of the object model can help politically. IMHO I don't care.

2020-09-30 19:30 UTC, didimitrie commented on Objects/Objects.csproj
> +    <Authors>AEC Systems</Authors>
Ditto I really don't care

2020-09-30 19:35 UTC, didimitrie commented on Objects/ObjectsKit.cs
> +    public ISpeckleConverter LoadConverter(string app)
And how would a connector load a convertor from a given kit without a hard coded reference, unless there's an interface that explicitly mandates this, and then gets implemented in every kit? Maybe there's a solution I missed, but IMHO this works fine at the moment. 

E.g., in Grasshopper I'm doing the following, which is super easy: 

- `Kit = KitManager.GetDefaultKit();` - this is implemented in Core, and it just returns the Objects kit. 
- thereafter `Converter = Kit.LoadConverter(Applications.Rhino);` to actually get a converter. 

There's another method I added, which makes it easy to get all the kits with converters for your given app (`var kits = KitManager.GetKitsWithConvertersForApp(Applications.Rhino);`)

And to swap them around in the future - when we'll expose an ui for them - it's easy: 
```
    private void SetConverterFromKit(string kitName)
    {
      if (kitName == Kit.Name) return;

      Kit = KitManager.Kits.FirstOrDefault(k => k.Name == kitName);
      Converter = Kit.LoadConverter(Applications.Rhino);

      Message = $"Using the \n{Kit.Name}\n Kit Converter";
      ExpireSolution(true);
    }
```

2020-10-01 12:49 UTC, izzylys requested changes

2020-10-01 12:49 UTC, izzylys commented on Objects/Objects.csproj
> +    <Exec Command="xcopy /Y /S $(TargetDir)$(AssemblyName).dll $(AppData)\Speckle\Kits\$(ProjectName)\" />
the quotes I think needa be in here in case the expanded path has spaces (eg my user folder is called `izzy lyseggen` so this fails for me without them)

doing this fixes it:
```xml
<Exec Command="xcopy /Y /S &quot;$(TargetDir)$(AssemblyName).dll&quot; &quot;$(AppData)\Speckle\Kits\$(ProjectName)\&quot;" />
```

2020-10-01 13:00 UTC, teocomi commented on Objects/Objects.csproj
> +    <Exec Command="xcopy /Y /S $(TargetDir)$(AssemblyName).dll $(AppData)\Speckle\Kits\$(ProjectName)\" />
good catch!

2020-10-01 13:24 UTC, izzylys approved these changes

2020-10-01 13:34 UTC, merged

2020-10-01 13:40 UTC, didimitrie commented
FFS this was not ready